config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :admin do

    root to: 'dashboard#show'

    resources :applicants, only: [:index, :show, :new, :create, :edit, :update] do
      scope module: :applicant_details do
        resources :applications, only: [:index, :show, :new, :create, :edit, :update]
        resources :applicant_requirements, only: [:new, :create, :edit, :update]
        resources :family_details, only: [:index, :new, :create, :edit, :update]
        resources :photos, only: [:index, :new, :create, :edit, :update]
        resources :employments, only: [:index, :new, :create, :edit, :update]

        # resources :contact_details, only: [:new, :create, :edit, :update]
        #
        # resources :requirements, only: [:new, :create, :edit, :update]
        # resources :documents, only: [:new, :create, :edit, :update]
        #
        resources :family_members, only: [:new, :create, :edit, :update]
        # resources :languages, only: [:new, :create, :edit, :update]
        #
        # resources :educations, only: [:new, :create, :edit, :update]
        # resources :meta_data, only: [:new, :create, :edit, :update]
        # resources :skills, only: [:new, :create, :edit, :update]
      end
    end

    resources :job_openings, only: [:index, :show, :new, :create, :edit, :update] do
      resources :requirements, only: [:new, :create, :edit, :update]
    end

    resource :lookups, only: [:show]

    namespace :lookups do

      resources :academic_degrees, only: [:index, :new, :create, :edit, :update]
      resources :academic_levels, only: [:index, :new, :create, :edit, :update]
      resources :blood_types, only: [:index, :new, :create, :edit, :update]
      resources :citizenships, only: [:index, :new, :create, :edit, :update]
      resources :civil_statuses, only: [:index, :new, :create, :edit, :update]
      resources :contact_types, only: [:index, :new, :create, :edit, :update]
      resources :countries, only: [:index, :new, :create, :edit, :update]
      resources :documents, only: [:index, :new, :create, :edit, :update]
      resources :languages, only: [:index, :new, :create, :edit, :update]
      resources :occupations, only: [:index, :new, :create, :edit, :update]
      resources :relationships, only: [:index, :new, :create, :edit, :update]
      resources :religions, only: [:index, :new, :create, :edit, :update]
      resources :schools, only: [:index, :new, :create, :edit, :update]
      resources :skills, only: [:index, :new, :create, :edit, :update]
      resources :skin_types, only: [:index, :new, :create, :edit, :update]
      resources :zodiacs, only: [:index, :new, :create, :edit, :update]

    end

    resources :users, only: [:index, :new, :create, :edit, :update] do
      match :lock, via: [:get, :patch], on: :member
      match :unlock, via: [:get, :patch], on: :member
      match :role, via: [:get, :patch], on: :member
    end

  end

  root to: "pages#index"

end

app/models/applicant_requirement.rb
class ApplicantRequirement < ApplicationRecord

  belongs_to :applicant, inverse_of: :applicant_requirements
  belongs_to :document, inverse_of: :applicant_requirements

  validates :applicant, :document, presence: true
  validates :document_id, uniqueness: { scope: :applicant_id }

end

app/controllers/admin/applicant_details/applicant_requirements_controller.rb
class Admin::ApplicantDetails::ApplicantRequirementsController < Admin::BaseController

  before_action :prepare_applicant
  before_action :prepare_applicant_requirement, only: [:edit, :update]

  def new
    @applicant_requirement = @applicant.applicant_requirements.new
    render action: :new, layout: false if request.xhr? == 0
  end

  def create
    @applicant_requirement = @applicant.applicant_requirements.new(applicant_requirement_params)
    if @applicant_requirement.save
      redirect_to admin_applicant_path(@applicant), notice: 'Successfully created record.'
    else
      render :new
    end
  end

  def edit
    render action: :edit, layout: false if request.xhr? == 0
  end

  def update
    if @applicant_requirement.update_attributes(applicant_requirement_params)
      redirect_to admin_applicant_path(@applicant), notice: 'Successfully updated record.'
    else
      render :edit
    end
  end

  private

  def prepare_applicant
    @applicant = Applicant.includes(:applicant_requirements).find(params[:applicant_id]).tap { |record| authorize record }
  end

  def prepare_applicant_requirement
    @applicant_requirement = @applicant.applicant_requirements.find(params[:id])
  end

  def applicant_requirement_params
    params.require(:applicant_requirement).permit(:document_id, :apply, :arrive, :expire, :note)
  end

end

app/controllers/admin/applicant_details/applications_controller.rb
class Admin::ApplicantDetails::ApplicationsController < Admin::BaseController

  before_action :prepare_applicant
  before_action :prepare_application, only: [:edit, :update]

  def index
    @applications = @applicant.applications
    @applicant_requirements = @applicant.applicant_requirements
    render action: :index, layout: false if request.xhr? == 0
  end

  def show
    @presenter = ApplicantDocumentsPresenter.new(params[:id])
    render action: :show, layout: false if request.xhr? == 0
  end

  def new
    @application = @applicant.applications.new
    render action: :new, layout: false if request.xhr? == 0
  end

  def create
    @application = @applicant.applications.new(application_params)
    if @application.save
      redirect_to admin_applicant_path(@applicant), notice: 'Successfully created record.'
    else
      render :new
    end
  end

  def edit
    render action: :edit, layout: false if request.xhr? == 0
  end

  def update
    if @application.update_attributes(application_params)
      redirect_to admin_applicant_path(@applicant), notice: 'Successfully updated record.'
    else
      render :edit
    end
  end

  private

  def prepare_applicant
    @applicant = Applicant.includes(:applications).find(params[:applicant_id]).tap { |record| authorize record }
  end

  def prepare_application
    @application = @applicant.applications.find(params[:id])
  end

  def application_params
    params.require(:application).permit(:job_opening_id, :applicant_code, :date_applied, :availability, :available)
  end

end

app/controllers/admin/applicant_details/employments_controller.rb
class Admin::ApplicantDetails::EmploymentsController < Admin::BaseController

  def index
    render text: 'at employments'
  end

end

app/controllers/admin/applicant_details/family_details_controller.rb
class Admin::ApplicantDetails::FamilyDetailsController < Admin::BaseController

  before_action :prepare_applicant
  before_action :prepare_family_detail, only: [:edit, :update]

  def index
    @family_detail = @applicant.family_detail || ApplicantFamilyDetail.new
    @family_members = @applicant.family_members
    render action: :index, layout: false if request.xhr? == 0
  end

  def new
    @family_detail = @applicant.build_family_detail
    render action: :new, layout: false if request.xhr? == 0
  end

  def create
    @family_detail = @applicant.build_family_detail(family_detail_params)
    if @family_detail.save
      redirect_to admin_applicant_path(@applicant), notice: 'Successfully created record.'
    else
      render :new
    end
  end

  def edit
    render action: :edit, layout: false if request.xhr? == 0
  end

  def update
    if @family_detail.update_attributes(family_detail_params)
      redirect_to admin_applicant_path(@applicant), notice: 'Successfully updated record.'
    else
      render :edit
    end
  end

  private

  def prepare_applicant
    @applicant = Applicant.includes(:family_detail, :family_members).find(params[:applicant_id]).tap { |record| authorize record }
  end

  def prepare_family_detail
    @family_detail = @applicant.family_detail
  end

  def family_detail_params
    params.require(:applicant_family_detail).permit(:sisters, :brothers, :no_in_fam, :children, :eldest, :youngest)
  end

end

app/controllers/admin/applicant_details/family_members_controller.rb
class Admin::ApplicantDetails::FamilyMembersController < Admin::BaseController

  before_action :prepare_applicant
  before_action :prepare_family_member, only: [:edit, :update]

  def new
    @family_member = @applicant.family_members.new
    render action: :new, layout: false if request.xhr? == 0
  end

  def create
    @family_member = @applicant.family_members.new(family_member_params)
    if @family_member.save
      redirect_to admin_applicant_path(@applicant), notice: 'Successfully created record.'
    else
      render :new
    end
  end

  def edit
    render action: :edit, layout: false if request.xhr? == 0
  end

  def update
    if @family_member.update_attributes(family_member_params)
      redirect_to admin_applicant_path(@applicant), notice: 'Successfully updated record.'
    else
      render :edit
    end
  end

  private

  def prepare_applicant
    @applicant = Applicant.includes(:family_members).find(params[:applicant_id]).tap { |record| authorize record }
  end

  def prepare_family_member
    @family_member = @applicant.family_members.find(params[:id])
  end

  def family_member_params
    params.require(:applicant_family_member).permit(:relationship_id, :occupation, :name, :age, :salary)
  end

end

app/controllers/admin/applicant_details/photos_controller.rb
class Admin::ApplicantDetails::PhotosController < Admin::BaseController

  def index
    render text: 'at photos'
  end

end

app/views/admin/applicant_details/applicant_requirements/_form.html.slim
.box.box-primary
  .modal-header.box-header.with-border

    button.close aria-label="Close" data-dismiss="modal" type="button"
      span aria-hidden="true"  ×

    h4.modal-title.box-title Application

  .modal-body.box-body
    .row
      .col-xs-12
        = f.association :document, collection: Document.active
    .row
      .col-xs-4
        .row
          .col-xs-12
            = f.input :apply, label: 'Date Applied (YYYY/MM/DD)' do
              div.input-group
                div.input-group-addon
                  = fa_icon 'calendar'
                = f.input_field :apply, as: :string, class: 'form-control datepicker pull-right', data: { 'date-min-date': 1.years.ago.strftime('%D'), 'date-max-date': Date.today.strftime('%D') }

          .col-xs-12
            = f.input :arrive, label: 'Date Received (YYYY/MM/DD)' do
              div.input-group
                div.input-group-addon
                  = fa_icon 'calendar'
                = f.input_field :arrive, as: :string, class: 'form-control datepicker pull-right', data: { 'date-min-date': 1.years.ago.strftime('%D'), 'date-max-date': 6.months.from_now.strftime('%D') }

          .col-xs-12
            = f.input :expire, label: 'Expiry Date (YYYY/MM/DD)' do
              div.input-group
                div.input-group-addon
                  = fa_icon 'calendar'
                = f.input_field :expire, as: :string, class: 'form-control datepicker pull-right', data: { 'date-min-date': 1.years.ago.strftime('%D'), 'date-max-date': 6.months.from_now.strftime('%D') }
      .col-xs-8
        = f.input :note, as: :text, input_html: { rows: 9 }


  .modal-footer.box-footer
    = f.submit 'Save', class: 'btn btn-flat btn-primary btn-block'

app/views/admin/applicant_details/applicant_requirements/edit.html.slim
- decorate(@applicant) do |applicant|
  - content_for :page_header do
    | Applications

  - content_for :breadcrumbs do
    li = link_to 'Applicants', admin_applicants_path
    li = link_to applicant.name, admin_applicants_path
    li = link_to 'Edit Applicant Document', edit_admin_applicant_applicant_requirement_path(applicant, @applicant_requirement)

  = simple_form_for @applicant_requirement, url: admin_applicant_applicant_requirement_path(applicant, @applicant_requirement), method: :patch do |f|
    = render 'form', f: f

app/views/admin/applicant_details/applicant_requirements/new.html.slim
- decorate(@applicant) do |applicant|
  - content_for :page_header do
    | Applications

  - content_for :breadcrumbs do
    li = link_to 'Applicants', admin_applicants_path
    li = link_to applicant.name, admin_applicants_path
    li = link_to 'New Applicant Document', new_admin_applicant_applicant_requirement_path(applicant)

  = simple_form_for @applicant_requirement, url: admin_applicant_applicant_requirements_path(applicant) do |f|
    = render 'form', f: f