config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  namespace :admin do

    root to: 'dashboard#show'

    resources :applicants, only: [:index, :show, :new, :create, :edit, :update] do
      scope module: :applicant_details do
        resources :applications, only: [:index, :show, :new, :create, :edit, :update]
        resources :applicant_requirements, only: [:new, :create, :edit, :update]
        resources :family_details, only: [:index, :new, :create, :edit, :update]
        resources :photos, only: [:index, :new, :create, :edit, :update]
        resources :employments, only: [:index, :new, :create, :edit, :update]

        # resources :contact_details, only: [:new, :create, :edit, :update]
        #
        # resources :requirements, only: [:new, :create, :edit, :update]
        # resources :documents, only: [:new, :create, :edit, :update]
        #
        resources :family_members, only: [:new, :create, :edit, :update]
        # resources :languages, only: [:new, :create, :edit, :update]
        #
        # resources :educations, only: [:new, :create, :edit, :update]
        # resources :meta_data, only: [:new, :create, :edit, :update]
        # resources :skills, only: [:new, :create, :edit, :update]
      end
    end

    resources :job_openings, only: [:index, :show, :new, :create, :edit, :update] do
      resources :requirements, only: [:new, :create, :edit, :update]
    end

    resource :lookups, only: [:show]

    namespace :lookups do

      resources :academic_degrees, only: [:index, :new, :create, :edit, :update]
      resources :academic_levels, only: [:index, :new, :create, :edit, :update]
      resources :blood_types, only: [:index, :new, :create, :edit, :update]
      resources :citizenships, only: [:index, :new, :create, :edit, :update]
      resources :civil_statuses, only: [:index, :new, :create, :edit, :update]
      resources :contact_types, only: [:index, :new, :create, :edit, :update]
      resources :countries, only: [:index, :new, :create, :edit, :update]
      resources :documents, only: [:index, :new, :create, :edit, :update]
      resources :languages, only: [:index, :new, :create, :edit, :update]
      resources :occupations, only: [:index, :new, :create, :edit, :update]
      resources :relationships, only: [:index, :new, :create, :edit, :update]
      resources :religions, only: [:index, :new, :create, :edit, :update]
      resources :schools, only: [:index, :new, :create, :edit, :update]
      resources :skills, only: [:index, :new, :create, :edit, :update]
      resources :skin_types, only: [:index, :new, :create, :edit, :update]
      resources :zodiacs, only: [:index, :new, :create, :edit, :update]

    end

    resources :users, only: [:index, :new, :create, :edit, :update] do
      match :lock, via: [:get, :patch], on: :member
      match :unlock, via: [:get, :patch], on: :member
      match :role, via: [:get, :patch], on: :member
    end

  end

  root to: "pages#index"

end

app/models/job_opening.rb
class JobOpening < ApplicationRecord

  belongs_to :country, inverse_of: :job_openings
  belongs_to :occupation, inverse_of: :job_openings

  has_many :requirements, inverse_of: :job_opening
  has_many :applications, inverse_of: :job_opening

  validates :country, :occupation, presence: true
  validates :occupation_id, uniqueness: { scope: :country_id }

  scope :active, -> { where(enabled: true) }

end

app/controllers/admin/job_openings_controller.rb
class Admin::JobOpeningsController < Admin::BaseController

  before_action :prepare_new_job_opening, only: [:new, :create]
  before_action :prepare_job_opening, only: [:show, :edit, :update]
  before_action :prepare_form, only: [:new, :create, :edit, :update]

  def index
    authorize JobOpening
    @job_openings = JobOpening.includes(:country, :occupation).order(country_id: :asc)
  end

  def show
    @requirements = @job_opening.requirements.includes(:document).order('documents.name asc')
    render action: :show, layout: false if request.xhr? == 0
  end

  def new
    render action: :new, layout: false if request.xhr? == 0
  end

  def create
    if @form.save(job_opening_params)
      redirect_to admin_job_openings_path, notice: 'Successfully created record.'
    else
      render :new
    end
  end

  def edit
    render action: :edit, layout: false if request.xhr? == 0
  end

  def update
    if @form.save(job_opening_params)
      redirect_to admin_job_openings_path, notice: 'Successfully updated record.'
    else
      render :edit
    end
  end

  private

  def prepare_new_job_opening
    @job_opening = JobOpening.new.tap { |record| authorize record }
  end

  def prepare_job_opening
    @job_opening = JobOpening.includes(:country, :occupation).find(params[:id]).tap { |record| authorize record }
  end

  def job_opening_params
    params.require(:job_opening).permit(:country_id, :occupation_id, :enabled)
  end

  def prepare_form
    @form = JobOpeningForm.new(@job_opening)
  end

end

app/views/admin/job_openings/_form.html.slim
.box.box-primary
  .modal-header.box-header.with-border

    button.close aria-label="Close" data-dismiss="modal" type="button"
      span aria-hidden="true"  ×

    h4.modal-title.box-title Job Opening Details

  .modal-body.box-body
    .row
      .col-xs-12
        = f.association :country, label: 'Country', collection: @form.countries
        = f.association :occupation, label: 'Occupation', collection: @form.occupations
        = f.input :enabled, label: 'Enabled?'

  .modal-footer.box-footer
    = f.submit 'Save', class: 'btn btn-flat btn-primary btn-block'

app/views/admin/job_openings/edit.html.slim
- decorate(@job_opening) do |job_opening|
  - content_for :page_header do
    | Editing Job Opening: #{job_opening.occupation_was.name} at #{job_opening.country_was.name}

  - content_for :breadcrumbs do
    li = link_to "Editing: #{job_opening.name}", edit_admin_job_opening_path(job_opening)

= simple_form_for @form.job_opening, url: admin_job_opening_path(@job_opening), method: :patch do |f|
  = render 'form', f: f

app/views/admin/job_openings/index.html.slim
- content_for :page_header do
  | Job Openings

- content_for :breadcrumbs do
  li = link_to 'Job Openings', admin_job_openings_path

.row
  .col-xs-12

    .box
      .box-header
        .box-title

        .box-tools
          .no-margin.pull-right
            = link_to 'Add new', new_admin_job_opening_path, class: 'btn btn-flat btn-primary', data: { toggle: 'modal', target: '.modal' }

      .box-body.no-padding

        table.table.table-hover.table-striped
          thead
            tr
              th
              th Status
              th Country
              th Occupation
          tbody
            - @job_openings.each do |job_opening|
              tr
                td
                  = link_to edit_admin_job_opening_path(job_opening), class: 'btn btn-flat btn-default', data: { toggle: 'modal', target: '.modal' } do
                    = fa_icon 'edit'
                    | Edit

                  = link_to admin_job_opening_path(job_opening), class: 'btn btn-flat btn-default' do
                    = fa_icon 'eye'
                    | Details
                td
                  - if job_opening.enabled?
                    span.label.label-success Enabled
                  - else
                    span.label.label-default Disabled
                td = job_opening.country.name
                td = job_opening.occupation.name

app/views/admin/job_openings/new.html.slim
- content_for :page_header do
  | New Job Openings

- content_for :breadcrumbs do
  li = link_to 'Job Openings', admin_job_openings_path
  li = link_to 'New', new_admin_job_opening_path

= simple_form_for @form.job_opening, url: admin_job_openings_path do |f|
  = render 'form', f: f

app/views/admin/job_openings/show.html.slim
- decorate(@job_opening) do |job_opening|
  - content_for :page_header do
    | Job Opening: #{job_opening.name}

  - content_for :breadcrumbs do
    li = link_to 'Job Openings', admin_job_openings_path
    li = link_to "#{job_opening.name}", admin_job_opening_path(job_opening)

  .row
    .col-xs-3
      .box.box-primary
        .box-header
          .box-title Details

        .box-body.box-profile
          ul.list-group.list-group-unbordered
            li.list-group-item
              b Country
              .pull-right = job_opening.country.name
            li.list-group-item
              b Occupation
              .pull-right = job_opening.occupation.name

    .col-xs-9
      .box
        .box-header
          .box-title

          .box-tools
            .no-margin.pull-right
              = link_to 'Add new requirement', new_admin_job_opening_requirement_path(job_opening), class: 'btn btn-flat btn-primary', data: { toggle: 'modal', target: '.modal' }

        .box-body.no-padding

          table.table.table-hover.table-striped
            thead
              th
              th Status
              th Document
            tbody
              - @requirements.each do |requirement|
                tr
                  td
                    = link_to edit_admin_job_opening_requirement_path(job_opening, requirement), class: 'btn btn-flat btn-default', data: { toggle: 'modal', target: '.modal' } do
                      = fa_icon 'edit'
                      | Edit

                  td
                    - if requirement.enabled?
                      span.label.label-success Enabled
                    - else
                      span.label.label-default Disabled
                  td = requirement.document.name